### ISSUE TITLE
Resnet+SALAD

### ISSUE THREAD

**Issue by YongDeng715** [serizba/salad#11]
Hello, I would like to reproduce the experiment of Resnet+SALAD in the paper, but cannot find the corresponding setting parameters about training a Resnet+SALAD model. So that I can compare the precision and detecting efficiency of DINOv2 backbone and Resnet backbone. Could you please provide training initialization hyperparameters set of  Resnet+SALAD?

**Comment by serizba** [comment]
Hi @YongDeng715 , when training a ResNet backbone we used the default hyperparameters from MixVPR.
