### ISSUE TITLE
Question about dataset orgatization

### ISSUE THREAD

**Issue by whu-lyh** [serizba/salad#3]
Wao. Amazing job! A new strategy for VPR. Thanks for your releasing codes. I wander how to process the multi-datasets and get the .npy file under dataset dir? Any instructions?

**Comment by serizba** [comment]
Hi @whu-lyh 

Do you mean how to create `.npy` files for a new dataset, or how to use existing `.npy` files?

**Comment by serizba** [comment]
These files are created manually. For SALAD, we just copied the `.npy` files from [GSV-Cities](https://github.com/amaralibey/gsv-cities). If you need to create new ones, you can just save the required info for the new dataset (image paths, indexes, ground truths..). 

I suggest loading the `.npy` files of an existing dataset to take a look to the desired labels to save.

**Comment by whu-lyh** [comment]
I found that the MSLS val dataset in your .npy file is different to the official released image data? The number of images is different. Did you do some data clean operation? Thanks.

**Comment by serizba** [comment]
As said, these files are copied from [GSV-Cities](https://github.com/amaralibey/gsv-cities).  You can take a look [here](https://github.com/amaralibey/MixVPR/issues/5#issuecomment-1438784599) for an explanation on the number of images.

**Comment by whu-lyh** [comment]
Oops, thanks.
