### ISSUE TITLE
DINOV2-Netvlad

### ISSUE THREAD

**Issue by pQWQq** [serizba/salad#4]
Hello, I want to reproduce the experiment in the paper, but cannot find the corresponding parameters. Can you provide the training code of DINOV2-Netvlad?

**Comment by Ahmedest61** [comment]
Hey, thanks for the great work. I'm also looking for DinoV2-NetVLAD training code.

**Comment by serizba** [comment]
Hi @pQWQq , you can use the same hyperparameters for training. Just append a NetVLAD aggregator.
